development: &default
  adapter: postgresql
  encoding: unicode
  database: enju_development
  pool: 5
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: enju_test

production:
  <<: *default
  database: enju_production
