development: &default
  adapter: postgresql
  encoding: unicode
  database: enju_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: enju_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
